Use smaller base image, based on Alpine
Azure-Samples/azure-voting-app-redis pull request #33
Opened 2018-12-10 20:02 UTC by pelithne

PR related to https://github.com/Azure-Samples/azure-voting-app-redis/issues/32

The only change is that the base image is changed to a smaller, Alpine based, version. This make the whole app more light weight without changing any features.

The change has been manually tested to work with the current tutorial: https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-prepare-app

However, the `docker images` commands used in the tutorial will render a slightly different output

2019-04-19 07:57 UTC, Overv commented
I don't see why this isn't being merged. It reduces the image size from 950 MB to 193 MB!

2019-04-19 19:15 UTC, pelithne commented
I can make a pull request to the original repo. I think (not sure) that I made some other changes that should not be merged though 🙂

/peter

________________________________
From: Alexander Overvoorde <notifications@github.com>
Sent: Friday, April 19, 2019 9:57 AM
To: Azure-Samples/azure-voting-app-redis
Cc: Peter Lithner; Author
Subject: Re: [Azure-Samples/azure-voting-app-redis] Use smaller base image, based on Alpine (#33)


I don't see why this isn't being merged. It reduces the image size from 950 MB to 193 MB!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure-Samples%2Fazure-voting-app-redis%2Fpull%2F33%23issuecomment-484798156&data=02%7C01%7Cpeter.lithner%40microsoft.com%7C610f1cc2a3124c244fa408d6c49cb8aa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636912574720994345&sdata=UIy54gS2rVe3Y%2FStSkcSxkGjacuPpN8qRRzSK951xlE%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKYMTODE3P6UJBFEAYURXALPRF3P5ANCNFSM4GJQKBAA&data=02%7C01%7Cpeter.lithner%40microsoft.com%7C610f1cc2a3124c244fa408d6c49cb8aa%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636912574720994345&sdata=Yh1Mwc53bOmnaXwu24lQN%2B%2FBWKNJUhhLoHwpktIEIpE%3D&reserved=0>.

2019-04-23 08:55 UTC, Overv commented
@pelithne What do you mean by original repo?

2019-04-23 08:56 UTC, Overv commented
@neilpeterson @iainfoulds What is stopping you from merging this?

2019-04-23 09:00 UTC, pelithne commented
@Overv I must have commented in my sleep :-), please disregard!

2019-04-23 15:57 UTC, iainfoulds commented
@Overv I wasn't a repo admin, so didn't receive notifications on this PR. I'm not sure why the original manifest used the larger Ubuntu image. We can prioritize this against other deliverables and review in order to merge it. Please be respectful in how you ask for assistance or updates.

2019-04-23 17:19 UTC, Overv commented
@iainfoulds I asked this way because I just thought it was strange that such an simple and obvious improvement appeared to be overlooked. I was going through the tutorial for AKS last week and the first thing I wondered was why such a simple web app required me to push such a huge image.

2023-07-21 16:58 UTC, zr-msft requested changes
@pelithne thank you so much for this contribution and apologies for the delayed response.

Please take a look at my feedback/questions.

2023-07-21 16:58 UTC, zr-msft commented on .github/workflows/main.yml
Is this file needed to support the base image change? or is it out of scope of this PR?

2023-07-21 16:58 UTC, zr-msft commented on azure-vote-all-in-one-redis.yaml
many of these changes have been incorporated by other merged PRs. Please rebase.

2023-07-21 16:58 UTC, zr-msft commented on azure-vote-all-in-one-redis.yaml
> +        image: privatepelithne.azurecr.io/azuredocs/azure-vote-front:latest
This should stay a reference to the image in MCR which will appear after a rebase:
https://github.com/Azure-Samples/azure-voting-app-redis/blob/master/azure-vote-all-in-one-redis.yaml#L60

2023-07-21 16:58 UTC, zr-msft commented on azure-vote/azure-vote/config_file.cfg
Please leave the original values and revert this change.

2023-07-21 16:58 UTC, zr-msft commented on workflow/main.yml
similar to `.github/workflows`, is this needed to support the proposed image change? or is this out of scope?

2023-10-02 15:29 UTC, closed without merging

2024-10-25 15:22 UTC, phemmmie commented
new update